### ISSUE TITLE
Get Images for Missing Cities

### ISSUE THREAD

**Issue by savannahostrowski** [spatialdev/osmquality-web#14]
Madison and Wilmington are missing for big images. Philadelphia, madison and wilmington for thumbnails

**Comment by Naomi77Paris** [comment]
![de_wilmington_thumbnail](https://user-images.githubusercontent.com/5613307/46430580-3bad3500-c6fe-11e8-8066-7a1e8d54e5c8.jpg)
![wi_madison_thumbnail](https://user-images.githubusercontent.com/5613307/46430581-3bad3500-c6fe-11e8-9b4a-99c2fbe63092.jpg)

![pa_philadelphia](https://user-images.githubusercontent.com/5613307/46430598-4c5dab00-c6fe-11e8-8687-090b01d2d404.jpg)
![wi_madison](https://user-images.githubusercontent.com/5613307/46430599-4c5dab00-c6fe-11e8-99ad-e4958f2b5174.jpg)
![de_wilmington](https://user-images.githubusercontent.com/5613307/46430600-4c5dab00-c6fe-11e8-8263-172ca42af9ac.jpg)
